services:
  - type: web
    name: cotizacionappweb
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: clave_secreta_para_sesiones
